apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: thats-a-wrap-media-api
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/thats-a-wrap/backend:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
