services:
  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:3.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki-data:/loki

  tempo:
    image: grafana/tempo:2.8.2
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./tempo-config.yml:/etc/tempo/tempo.yml:ro
      - tempo-data:/var/tempo

  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/production.json:ro

volumes:
  loki-data:
  tempo-data:
